In [1]:
import numpy as np
from sklearn.datasets import load_iris
import pandas as pd

In [2]:
df = pd.read_csv("P:/tech/datasets/titanic_prep.csv")

In [3]:
df.head()

Unnamed: 0  Survived  Pclass   Age  SibSp  Parch     Fare  Sex_male  \
0           0         0       3  22.0      1      0   7.2500         1   
1           1         1       1  38.0      1      0  71.2833         0   
2           2         1       3  26.0      0      0   7.9250         0   
3           3         1       1  35.0      1      0  53.1000         0   
4           4         0       3  35.0      0      0   8.0500         1   

   Embarked_Q  Embarked_S  
0           0           1  
1           0           0  
2           0           1  
3           0           1  
4           0           1

In [4]:
x = df.drop(["Survived","Unnamed: 0"],axis =1).values
y = df["Survived"].values

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25)

In [7]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [8]:
class ANNclassifier():
    def __init__(self,in_size,out_size,no_examples):
        self.in_size = in_size
        self.out_size = out_size
        self.w = np.random.rand(in_size,out_size)
        self.b = np.random.rand(1,1)
        self.no_examples = no_examples
        
 

    def fit(self,x,y,lr,epochs = 10000,per_epoch = 100):
        for i in range(epochs):
            cost = 0
            ##Forward propagation
            z = np.dot(self.w.T,x) + self.b
            a = 1/(1+np.exp(-z))
            
            ##Computing loss
            cost = (- 1 / self.no_examples) * np.sum(y * np.log(a) + (1 - y) * (np.log(1 - a))) 
            
            if i%per_epoch == 0:
                print(f"train_loss is{cost}")
            
            ##Back propagstion
            dw = (1 / self.no_examples) * np.dot(x, (a - y).T)
            db = (1 / self.no_examples) * np.sum(a - y) 
            
            ##updating weights
            self.w = self.w - lr*dw
            self.b = self.b - lr*db
        
        
    def Predict(self,x_test):
        
        z = np.dot(self.w.T,x_test) + self.b
        return 1/(1+np.exp(-z))

        
        
        

In [9]:
iris_classifier = ANNclassifier(x.shape[1],1,x.shape[0])

In [10]:
iris_classifier.fit(x_train.T,y_train.reshape(1,-1),lr=2)

train_loss is0.8943457790838831
train_loss is0.3437479971537183
train_loss is0.33697748197255406
train_loss is0.3340222478249688
train_loss is0.3325936530075297
train_loss is0.331862468393187
train_loss is0.3314682308616308
train_loss is0.3312444186490398
train_loss is0.3311105079436952
train_loss is0.3310260473855072
train_loss is0.33097000467412363
train_loss is0.33093106903780883
train_loss is0.33090293865374504
train_loss is0.33088196462256547
train_loss is0.33086594362312455
train_loss is0.33085348478833415
train_loss is0.3308436699306354
train_loss is0.33083586662638736
train_loss is0.33082962250610354
train_loss is0.3308246035623743
train_loss is0.33082055685098083
train_loss is0.33081728705328994
train_loss is0.33081464114500614
train_loss is0.3308124979628585
train_loss is0.3308107608390022
train_loss is0.33080935223117564
train_loss is0.3308082097016113
train_loss is0.3308072828409184
train_loss is0.3308065308757784
train_loss is0.330805920785268
train_loss is0.33080542580407

In [11]:
y_pred = iris_classifier.Predict(x_test.T)

In [12]:
y_pred[y_pred >= 0.5] = 1
y_pred[y_pred < 0.5] = 0

In [13]:
y_pred

array([[0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0.,
        0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
        0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0.,
        0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0.,
        1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0.,
        1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0.,
        0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0.,
        1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1.,
        0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 

In [14]:
y_test

array([0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1], dtype=int64)

In [15]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [16]:
confusion_matrix(y_pred.reshape(-1,1),y_test.reshape(-1,1))

array([[121,  28],
       [ 19,  55]], dtype=int64)

In [17]:
accuracy_score(y_pred.reshape(-1,1),y_test.reshape(-1,1))

0.7892376681614349