In [1]:
import numpy as np
from sklearn.datasets import load_iris
import pandas as pd

In [2]:
df = pd.read_csv("titanic_prep.csv")

In [3]:
df.head()

Unnamed: 0  Survived  Pclass   Age  SibSp  Parch     Fare  Sex_male  \
0           0         0       3  22.0      1      0   7.2500         1   
1           1         1       1  38.0      1      0  71.2833         0   
2           2         1       3  26.0      0      0   7.9250         0   
3           3         1       1  35.0      1      0  53.1000         0   
4           4         0       3  35.0      0      0   8.0500         1   

   Embarked_Q  Embarked_S  
0           0           1  
1           0           0  
2           0           1  
3           0           1  
4           0           1

In [4]:
x = df.drop(["Survived","Unnamed: 0"],axis =1).values
y = df["Survived"].values

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25)

In [7]:
y_train[y_train >1] =0
y_test[y_test>1] = 0

In [8]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [9]:
class ANNclassifier():
    def __init__(self,in_size,out_size,no_examples):
        self.in_size = in_size
        self.out_size = out_size
        self.w = np.random.rand(in_size,out_size)
        self.b = np.random.rand(1,1)
        self.no_examples = no_examples
        
 

    def fit(self,x,y,lr,epochs = 2000,per_epoch = 100):
        for i in range(epochs):
            cost = 0
            ##Forward propagation
            z = np.dot(self.w.T,x) + self.b
            a = 1/(1+np.exp(-z))
            
            ##Computing loss
            cost = (- 1 / self.no_examples) * np.sum(y * np.log(a) + (1 - y) * (np.log(1 - a))) 
            
            if i%per_epoch == 0:
                print(f"train_loss is{cost}")
            
            ##Back propagstion
            dw = (1 / self.no_examples) * np.dot(x, (a - y).T)
            db = (1 / self.no_examples) * np.sum(a - y) 
            
            ##updating weights
            self.w = self.w - lr*dw
            self.b = self.b - lr*db
        
        
    def Predict(self,x_test):
        
        z = np.dot(self.w.T,x_test) + self.b
        return 1/(1+np.exp(-z))

        
        
        

In [10]:
iris_classifier = ANNclassifier(x.shape[1],1,x.shape[0])

In [11]:
iris_classifier.fit(x_train.T,y_train.reshape(1,-1),lr=1.5)

train_loss is0.6638857269082373
train_loss is0.35323885798988974
train_loss is0.34448540756017515
train_loss is0.340030248170643
train_loss is0.3374807478386522
train_loss is0.33596086354597265
train_loss is0.33502849024044556
train_loss is0.334443161857033
train_loss is0.3340683835978099
train_loss is0.33382417964190386
train_loss is0.3336624842989453
train_loss is0.333553792074603
train_loss is0.33347965953609915
train_loss is0.333428373499555
train_loss is0.33339238873493116
train_loss is0.3333667815331483
train_loss is0.3333482999643609
train_loss is0.3333347716021607
train_loss is0.33332472911510425
train_loss is0.3333171706702651


In [12]:
y_pred = iris_classifier.Predict(x_test.T)

In [13]:
y_pred[y_pred >= 0.5] = 1
y_pred[y_pred < 0.5] = 0

In [14]:
y_pred

array([[1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1.,
        1., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0.,
        1., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
        0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 1., 1.,
        0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0.,
        1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0.,
        0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1.,
        0., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
        1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 

In [15]:
y_test

array([0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0], dtype=int64)

In [16]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [17]:
confusion_matrix(y_pred.reshape(-1,1),y_test.reshape(-1,1))

array([[113,  27],
       [ 14,  69]], dtype=int64)

In [18]:
accuracy_score(y_pred.reshape(-1,1),y_test.reshape(-1,1))

0.8161434977578476